version: '4.22'

services:
  db:
    container_name: alembic_postgresql_db
    image: postgres:12
    restart: always
    ports:
      - 5435:5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: alembic_pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - 5050:80
    depends_on:
      - db
  app:
    container_name: alembic_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: